FROM ruby:2.4-alpine
ENV APP_HOME /notes
ENV RAILS_ENV production
ENV RACK_ENV production
ENV NODE_ENV production
RUN set -ex \
  && apk add --no-cache libpq nodejs bash
RUN mkdir $APP_HOME
WORKDIR $APP_HOME
RUN npm install --global yarn
ADD Gemfile $APP_HOME/Gemfile
ADD Gemfile.lock $APP_HOME/Gemfile.lock
RUN bundle install --without test, development
ADD . $APP_HOME
RUN bundle exec rails assets:precompile
CMD ["bundle", "exec", "puma"]
