FROM ruby:2.4.2
ENV APP_HOME /notes
ENV RAILS_ENV production
RUN apt-get update -qq && apt-get install -y build-essential libpq-dev nodejs
RUN mkdir $APP_HOME
WORKDIR $APP_HOME
RUN npm install --global yarn
ADD Gemfile $APP_HOME/Gemfile
ADD Gemfile.lock $APP_HOME/Gemfile.lock
RUN bundle install --without test, development
ADD . $APP_HOME
RUN bundle exec rails assets:precompile
CMD ["bundle", "exec", "puma"]
